//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Counter
{
	public virtual object count
	{
		get;
		set;
	}

	public virtual object min
	{
		get;
		set;
	}

	public virtual object max
	{
		get;
		set;
	}

	public virtual void Increament()
	{
		throw new System.NotImplementedException();
	}

}

